version: "2"
services:
  mariadb:
    build: db
    volumes:
      - ./db/:/root/db/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"

  httpd:
    build: php
    ports:
      - "8080:80"
    volumes:
      - ./src/dexonline/:/var/www/html


# httpd:
# docker-php-ext-install -j5 pdo mysqli
